### ISSUE TITLE
Clash with 'nerian_stereo' when installed at the same time

### ISSUE THREAD

**Issue by gavanderhoorn** [nerian-vision/nerian_sp1#1]
I'm not a user of this package (or of `nerian_stereo`), but I just ran into this (while running a `apt-get install ros-kinetic-*` on a test system) so I thought I'd report it.

Trying to install the debians of both `nerian_sp1` and `nerian_stereo` at the same time results in the following error:

```
Unpacking ros-kinetic-nerian-stereo (2.0.1-0xenial-20171004-154135-0800) ...
dpkg: error processing archive /var/cache/apt/archives/ros-kinetic-nerian-stereo_2.0.1-0xenial-20171004-154135-0800_amd64.deb (--unpack):
 trying to overwrite '/opt/ros/kinetic/lib/libvisiontransfer.so', which is also in package ros-kinetic-nerian-sp1 1.6.2-0xenial-20170613-183651-0800
```

It would appear both are trying to install `libvisiontransfer.so`, which is not possible.

**Comment by nerian-vision** [comment]
Thanks for reporting. I'll look for a solution.

**Comment by nerian-vision** [comment]
Has been resolved.
